APP_NAME = "RP Binder"

APP_VERSION_ENV = "RPB_APP_VERSION"
UPDATE_INFO_URL_ENV = "RPB_UPDATE_INFO_URL"

DEFAULT_WINDOW_WIDTH = 1000
DEFAULT_WINDOW_HEIGHT = 620
MIN_WINDOW_WIDTH = 980
MIN_WINDOW_HEIGHT = 620

LEFT_COLUMN_MIN_WIDTH = 230
CENTER_COLUMN_MIN_WIDTH = 300
RIGHT_COLUMN_MIN_WIDTH = 370

STATUS_MESSAGE_MS = 1500
UPDATE_CHECK_TIMEOUT_SECONDS = 3

HOTKEY_PASTE_SETTLE_SECONDS = 0.08
HOTKEY_CLIPBOARD_RESTORE_SECONDS = 0.06
PANIC_HOTKEY_DEFAULT = "End"

PASTE_ENTER_DEFAULT_DELAY_MS = 120
PASTE_ENTER_MIN_DELAY_MS = 0
PASTE_ENTER_MAX_DELAY_MS = 5000

CHAT_OPEN_HOTKEY_DEFAULT = "T"
CHAT_OPEN_DELAY_DEFAULT_MS = 0
CHAT_OPEN_DELAY_MIN_MS = 0
CHAT_OPEN_DELAY_MAX_MS = 5000
